# Dependencies
markdown:         redcarpet
highlighter:      pygments.rb

# Permalinks
permalink:        pretty

# Setup
title:            Sam Hinshaw
tagline:          "Science & Front-End"
description:      'The personal website of Sam Hinshaw. I like to talk tech.'
url:              http://samhinshaw.com
baseurl:          /

author:
  name:  Sam Hinshaw
  twitter: samhinshaw

paginate:         5
paginate_path: "/:num/"


# Custom vars
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate
  - jekyll-archives
  - redcarpet
  - pygments.rb


version:          2.1.0

github:
  repo:           https://github.com/samhinshaw/website
