# Dependencies
markdown:         redcarpet
highlighter:      pygments.rb

# Permalinks
permalink:        pretty

# Setup
title:            Sam Hinshaw
tagline:          "Science & Development"
description:      'Passionate about tech, science, and development. Graduate Student at UBC.'
url:              http://samhinshaw.com
baseurl:          /

author:
  name:  Sam Hinshaw
  twitter: samhinshaw

paginate:         5
paginate_path: "/posts/page:num/"


# Custom vars
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate
  - jekyll-archives
  - redcarpet
  - pygments.rb

github:
  repo:           https://github.com/samhinshaw/website
